### ISSUE TITLE
Missing option name in icinga2_master/tasks/main.yml

### ISSUE THREAD

**Issue by mdicss** [Linuxfabrik/lfops#105]
In line 38 in icinga2_master/tasks/main.yml the name of the option is missing. Line 38 should be:
      --database={{ icinga2_master__database_name | quote }}

**Comment by markuslf** [comment]
No, just the order of the parameters is a bit stupid. The synopsis of the mysql command is `mysql [options] db_name`. I corrected the sort order to make it clearer.

**Comment by mdicss** [comment]
Ok, thank you. My yaml-editor in eclipse reported an error in the file, so I thought, the option is missing. You are right, the '--database'-option is optional and with the changed order, the editor no longer shows an error.
