### ISSUE TITLE
Cloud: Create VM-Volumes with GPT instead of MS-DOS Partition Table

### ISSUE THREAD

**Issue by markuslf** [Linuxfabrik/lfops#117]
If you try to add an OpenStack volume to an existing machine, at least `infomaniak_vm` creates MS-DOS partition tables (if I remember correctly). Creating partitions > 2 TB using LFOps is not possible. Don't know if it's an LFOps issue or our images.

**Comment by NavidSassan** [comment]
should be fixed when using the new https://github.com/Linuxfabrik/kickstart files
