### ISSUE TITLE
CONTRIBUTING, all roles: define how to handle "OS not supported"

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/lfops#19]
Currently, we are partly relying on the os-specific tasks. However, this only works if we can include the tasks at the start of the role, and that is not possible for the `monitoring_plugins` role.
We also are adding `when` statements based on the OS in the playbooks, is that enough?

**Comment by markuslf** [comment]
Since this is how many of the old roles worked, this should be sufficient to control some tasks depending on the operating system family and other attributes.

**Comment by NavidSassan** [comment]
We will rely on "Tested on" section in the README, and won't enforce anything in the code. If the role works on a different OS, that's an added bonus and we can add it to the README.

In application playbooks (eg `playbooks/duplicity.yml`) or playbooks with a single role (eg `playbooks/at.yml`), the final role should never be skipped based on OS-variables.
