### ISSUE TITLE
role:postfix: Compare to linux-system-roles.postfix

### ISSUE THREAD

**Issue by markuslf** [Linuxfabrik/lfops#36]
Is it necessary to have our own Postfix role?

**Comment by NavidSassan** [comment]
probably not, somehow missed that one. will have a look

**Comment by NavidSassan** [comment]
sadly that postfix role only allows changes to the `/etc/postfix/main.cf` via `postconf`, as far as I can see there is no way to adjust the `/etc/postfix/sasl_passwd` and run `postmap`.
