### ISSUE TITLE
role:sshd: Compare to linux-system-roles.sshd

### ISSUE THREAD

**Issue by markuslf** [Linuxfabrik/lfops#39]
Is it necessary to have our own sshd role?

**Comment by NavidSassan** [comment]
where did you find that sshd role? i only find ssh (for the ssh client, not sshd server: https://github.com/linux-system-roles/ssh

**Comment by markuslf** [comment]
I did a `dnf -y install rhel-system-roles`. A subsequent `ansible-galaxy list` shows:
- ...
- linux-system-roles.ssh, (unknown version)
- linux-system-roles.sshd, (unknown version)
- ...

All located in `/usr/share/ansible/collections/ansible_collections/redhat/rhel_system_roles/roles`.

**Comment by NavidSassan** [comment]
From the README it seems to be this role: https://galaxy.ansible.com/willshersystems/sshd

**Comment by NavidSassan** [comment]
we'll keep using our role for now
