### ISSUE TITLE
role:duplicity: duba.json is not re-configured correctly

### ISSUE THREAD

**Issue by markuslf** [Linuxfabrik/lfops#59]
Assume you have a duba.json with just the defaults, no further host-based `duplicity__` config settings. The generated config then looks like this:

```
...
  "backup_sources": [
    {
     	"divide": false,
        "path": "/backup"
    },
    {
     	"divide": false,
        "path": "/etc"
    },
    {
     	"divide": false,
        "path": "/home"
    },
    {
     	"divide": false,
        "path": "/opt"
    },
    {
     	"divide": false,
        "path": "/root"
    },
    {
     	"divide": false,
        "path": "/var/spool/cron"
    },
...
```

Configure a host-specific setting:

```
duplicity__host_backup_sources:
  - path: '/opt'
    divide: true
```

A wrong config file is generated (`/opt` is configured twice with contrary values):

```
  "backup_sources": [
    {
     	"divide": false,
        "path": "/backup"
    },
    {
     	"divide": false,
        "path": "/etc"
    },
    {
     	"divide": false,
        "path": "/home"
    },
    {
     	"divide": false,
        "path": "/opt"
    },
    {
     	"divide": false,
        "path": "/root"
    },
    {
     	"divide": false,
        "path": "/var/spool/cron"
    },
    {
     	"divide": true,
        "path": "/opt"
    }
...
```

Even if you change `duba.json` on the server and delete 

```
    {
     	"divide": false,
        "path": "/opt"
    },
```

beforehand.

**Comment by NavidSassan** [comment]
sadly currently a known limitation - see section in the main readme.
its not easily possible to distinguish which setting should be use using jinja2 filters - we would need a python scripts, something like debops does.

as a workaround you can manually set `duplicity__role_backup_sources` in the host_vars.
