### ISSUE TITLE
role:python: On RHEL 8+, don't install `python3`. Instead install `python38` or `python39` explicitly

### ISSUE THREAD

**Issue by markuslf** [Linuxfabrik/lfops#62]
Otherwise Python 3.6 is installed, which might be too old nowadays, and you run into problems like that described in https://github.com/Linuxfabrik/monitoring-plugins/issues/587

Python 3.9 preferred.

If multiple Python versions are installed in parallel, set `python3` to `python3.8` or `python3.9`.

**Comment by markuslf** [comment]
Also we get this sometimes if using Python 3.6: `/usr/local/lib/python3.6/site-packages/smbprotocol/connection.py:18: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
`

**Comment by markuslf** [comment]
Also install `python38-psutil` or `python39-psutil` for the monitoring-plugins.

**Comment by NavidSassan** [comment]
according to https://peps.python.org/pep-0602/#long-term-support-releases there are no explicit LTS versions

**Comment by NavidSassan** [comment]
we will keep using just python3, as setting the default to python3.9 makes the use of ansible a lot harder. instead we will package the monitoring-plugins with python and all required modules.

**Comment by markuslf** [comment]
The monitoring-plugins should be deployed via .rpm/.deb per default. This makes everything a lot easier than before - so we also only need to install python when we really need it.
