### ISSUE TITLE
role:acme_sh: is acme.sh automatically updated?

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/lfops#74]
should we enable this? -> needs to documented

**Comment by markuslf** [comment]
Yes, that would be nice. Question is how: using a systemd-timer just for acme.sh (once a month would be sufficient), or using a common/more generalized LFOps systemd update-timer which tries to update all non-package-manager-installed-software on a regulary basis one by one (I prefer the former).

**Comment by NavidSassan** [comment]
we could run the update command before renewal (once a month, as a `ExecStartPre` in the existing service), and before issuing new certs in the ansible role

**Comment by markuslf** [comment]
Would be elegant, something like `ExecStartPre=acme_sh --upgrade` (hint: there is also an `--auto-upgrade` parameter).

```
$ acme.sh --help | grep upgrade
  --upgrade                Upgrade acme.sh to the latest code from https://github.com/acmesh-official/acme.sh.
  --auto-upgrade [0|1]              Valid for '--upgrade' command, indicating whether to upgrade automatically in future. Defaults to 1 if argument is omitted.

```
