### ISSUE TITLE
role:icinga2_agent: On Debian User nagios does not exist when certs folder is created

### ISSUE THREAD

**Issue by axxeo** [Linuxfabrik/lfops#77]
If role is run on newly created Debian Host, the following Error occurs:
```
fatal: [host]: FAILED! => changed=false 
  gid: 0
  group: root
  mode: '0755'
  msg: 'chown failed: failed to look up user nagios'
  owner: root
  path: /var/lib/icinga2/certs
  size: 4096
  state: directory
  uid: 0
```

**Comment by NavidSassan** [comment]
should be fixed, please test :)

**Comment by axxeo** [comment]
This works. Is it possible to create pull requests for feature issues?

Can you rename the task: `linuxfabrik.lfops.icinga2_agent : dnf install icinga2 -y` to `linuxfabrik.lfops.icinga2_agent : install icinga2 -y` because Debians Packetmanager is apt

**Comment by NavidSassan** [comment]
Hi, of course, pull requests are very welcome :)

I will quickly adjust the task name.
